title: Farhad Hagverdi | Born to be gay
author: Farhad Hagverdi
email: joao@neto.pt
description: >-
  Friendly neighborhood arab.

social:
  twitter: joaomlneto
  facebook: joaomlneto
  instagram: joaomlneto
  github: joaomlneto
  linkedin:

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  images:
    output: true
