title: Farhad Hagverdi | Film Editor
author: Farhad Hagverdi
email: joao@neto.pt
description: >-
  Freelance Film Editor

social:
  twitter: joaomlneto
  facebook: joaomlneto
  instagram: joaomlneto
  github: joaomlneto
  linkedin:

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  images:
    output: true
